### ISSUE TITLE
How to use azurechat without Cosmos DB, Azure AI Document and Azure Cognitive

### ISSUE THREAD

**Issue by Gt180Full** [microsoft/azurechat#301]
I am interested in using azurechat in a company scenario, but it has not been historically approved (Cosmo DB) and due to region reasons I cannot use the Document intelligence and Search service.

In this regard, I would like help from the community to create a simpler scenario containing only Azure OpenIA plus Web App with the azurechat interface.

**Comment by bwitzig-zen** [comment]
@Gt180Full I would suggest using the default azurechat bot instead of this one as you would need those features for this app to work with the majority of functionality.

**Comment by bwitzig-zen** [comment]
@Gt180Full 
In order for chat history to work, you need to store the chatlogs somewhere, for this project it uses Cosmos DB. In addition the file upload functionality requires Document intelligence/search to work. The new extensions feature also utilizes this functionality to allow for search of internal documents with AI. 

These are the primary benefits over the "default" bot you can create using the azure AI studio "one click deploy"

As all of these components are key for this particular bot to work. I don't think it makes a lot of sense to utilize this repo in your environment if you are not able to enable the deployment requirements . The default bot you get in the azure can be deployed without the search service, without the document intelligence, and without Cosmos DB. Just the functionality will be more limited due to this.
