### ISSUE TITLE
ERROR: deployment failed: failing invoking action 'provision', error deploying infrastructure: deploying to subscription:

### ISSUE THREAD

**Issue by na20aak-herts** [microsoft/azurechat#373]
I am trying to deploy to deploy the solution in a customers tenant using the Azure CLI but I am receiving the error below. I have owner access on the subscription so not sure why I am getting the error. Any help is greatly appreciated, thanks.

![image](https://github.com/microsoft/azurechat/assets/154440888/1ce23dd6-514f-4672-9e40-7f1ed5e30721)

**Comment by vlad-tsoy** [comment]
This can also be due to Entra ID being in another subscription where you are not the owner. You must get elevated permission to access that subscription to make security changes. I have a Cloud Application Administrator role that I activate through PIM when provisioning resources or making security-related changes.

**Comment by na20aak-herts** [comment]
@vlad-tsoy, @robbinsjd4. Thank you both for the help, I have managed to fix it with your advice.
